# docker run -p 127.0.0.1:8080:8080
# -e KC_BOOTSTRAP_ADMIN_USERNAME=admin
# -e KC_BOOTSTRAP_ADMIN_PASSWORD=admin
# quay.io/keycloak/keycloak:26.5.3
# start-dev

services:
    keycloak:
        image: quay.io/keycloak/keycloak:26.5.3
        container_name: keycloak
        environment:
            - KC_BOOTSTRAP_ADMIN_USERNAME=admin
            - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
        command: start-dev
        ports:
            - 18080:8080